### Mostrar todos os filmes cadastrados
GET http://localhost:3067/all-movies

### Adicionar um novo filme
POST http://localhost:3067/create-movie
Content-Type: application/json

{
    "title": "Star Wars: Uma Nova Esperança",
    "genre": "Ficção Científica",
    "duration": 121,
    "age_rating": "10"
}

### Editar um filme (troque o :1 pelo id do filme que quer editar)
PUT http://localhost:3067/edit-movie/1
Content-Type: application/json

{
    "title": "O Poderoso Chefão",
    "genre": "Drama",
    "duration": 175,
    "age_rating": "18"
}

### Apagar um filme (troque o :1 pelo id do filme que quer apagar)
DELETE http://localhost:3067/delete-movie/1
